
import pygame

SHAKE_DURATION = 800
SHAKE_INTENSITY = 2
SHAKE_FREQUENCY = 5

START_NEW_GAME_EVENT = pygame.USEREVENT + 3
END_GAME_EVENT = pygame.USEREVENT + 4
EXIT_GAME_EVENT = pygame.USEREVENT + 5
SHAKE_EVENT = pygame.USEREVENT + 6
SHIP_COLLISION_EVENT = pygame.USEREVENT + 7


FPS = 60
WIDTH = 800
HEIGHT = 600
WSCALE = 5

MAX_ASTEROID_PER_LEVEL = 50
background_color = (10, 10, 10)
outline_color = (220, 220, 220)
fill_color = (0, 0, 0)