
import pygame

SHAKE_DURATION = 800
SHAKE_INTENSITY = 2
SHAKE_FREQUENCY = 5

BOX2D_ASTEROID_USER_DATA = 'ASTEROID'
BOX2D_SHIP_USER_DATA = 'SHIP'

START_NEW_GAME_EVENT = pygame.USEREVENT + 3
END_GAME_EVENT = pygame.USEREVENT + 4
EXIT_GAME_EVENT = pygame.USEREVENT + 5
SHAKE_EVENT = pygame.USEREVENT + 6


FPS = 60
WIDTH = 800
HEIGHT = 600
WSCALE = 5
MAX_ASTEROID_ON_SCREEN = 20
MAX_ASTEROID_PER_LEVEL = 50
backgroundColor = (10, 10, 10)
outlineColor = (220, 220, 220)
fillColor = (0, 0, 0)